project:
  type: default
 
format:
  html:
    self-contained: true
    toc: true
    toc-depth: 3
    toc-title: "Pipeline Steps"
    code-fold: false
    theme: cosmo
    highlight-style: github
 
execute:
  echo: true
  warning: false
  message: false
  cwd: "~/GitHub/str2phy_tools_tutorial_v0" # set the working directory to the root of the project
